### ISSUE TITLE
How do you get selected_stftabs_w100h50_0.4.txt.cluster_centres?

### ISSUE THREAD

**Issue by wsxwd** [JunweiLiang/videoSync#1]
In your project, you use selected_stftabs_w100h50_0.4.txt.cluster_centres as your kmeans cluster_centres. However, how do you get it? Is it can be used for other videosync project?

**Comment by JunweiLiang** [comment]
We run K-means on the large dataset we have. If the other dataset is large enough (> 40 hours) then it would be better to compute new centers.
